server:
  port: 2024

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_security?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

